{
 "title": "TaaSim - Demo Dashboard",
 "tags": [
  "demo",
  "final"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Vehicle Map",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "SELECT event_time AS time, lat, lon, status, taxi_id FROM taasim.vehicle_positions WHERE city='casablanca' PER PARTITION LIMIT 1 ALLOW FILTERING",
     "keyspace": "taasim"
    }
   ]
  },
  {
   "title": "Demand Heatmap",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "SELECT window_start AS time, zone_id, centroid_lat, centroid_lon, ratio FROM taasim.demand_zones WHERE city='casablanca' PER PARTITION LIMIT 1 ALLOW FILTERING",
     "keyspace": "taasim"
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "SELECT label, value FROM taasim.kpi_aggregates WHERE kpi_name IN ('trips_24h', 'avg_eta', 'match_rate_5s', 'top_zone') ALLOW FILTERING",
     "keyspace": "taasim"
    }
   ]
  },
  {
   "title": "ML Forecast vs Actual Demand",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "target": "SELECT window_start AS time, CAST(zone_id AS text) AS zone, pending_requests AS actual, forecasted_demand AS predicted FROM taasim.demand_zones WHERE city='casablanca' PER PARTITION LIMIT 1 ALLOW FILTERING",
     "keyspace": "taasim"
    }
   ]
  }
 ]
}