import argparse
import csv
import os
from functools import lru_cache

import requests
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import ArrayType, DoubleType, StructField, StructType

# Source (Porto) bounds from dataset profiling
PORTO_LON_MIN, PORTO_LON_MAX = -8.690, -8.550
PORTO_LAT_MIN, PORTO_LAT_MAX = 41.100, 41.190
OSRM_BASE_URL = "http://localhost:5000"


def parse_args():
    parser = argparse.ArgumentParser(description="Issue 4 Porto to Casablanca zone remapper")
    parser.add_argument("--input-path", default="s3a://raw/porto-trips/", help="Input Porto CSV path")
    parser.add_argument(
        "--output-path",
        default="s3a://curated/casablanca-trips-remapped/",
        help="Output remapped parquet path",
    )
    parser.add_argument("--s3-endpoint", default="http://minio:9000", help="S3/MinIO endpoint")
    parser.add_argument("--s3-access-key", default="minioadmin", help="S3/MinIO access key")
    parser.add_argument("--s3-secret-key", default="minioadmin123", help="S3/MinIO secret key")
    parser.add_argument(
        "--zone-mapping-path",
        default="data/zone_mapping.csv",
        help="Path to zone_mapping.csv generated by scripts/generate_zone_mapping.py",
    )
    parser.add_argument(
        "--osrm-base-url",
        default="http://localhost:5000",
        help="OSRM base URL (use http://osrm-backend:5000 when running in docker compose network)",
    )
    return parser.parse_args()


@lru_cache(maxsize=200000)
def _snap_cached(lon_key, lat_key):
    return _snap_uncached(lon_key, lat_key)


def _snap_uncached(lon, lat):
    """
    Calls the local OSRM API to snap translated coordinates to the actual road network.
    """
    url = f"{OSRM_BASE_URL}/nearest/v1/driving/{lon},{lat}?number=1"
    try:
        response = requests.get(url, timeout=2)
        if response.status_code == 200:
            data = response.json()
            if data.get("code") == "Ok" and data.get("waypoints"):
                snapped_lon = data["waypoints"][0]["location"][0]
                snapped_lat = data["waypoints"][0]["location"][1]
                return float(snapped_lon), float(snapped_lat)
    except Exception:
        # Silent fallback keeps batch processing alive if OSRM is unreachable.
        pass

    return float(lon), float(lat)


def snap_to_road(lon, lat):
    lon_key = round(float(lon), 6)
    lat_key = round(float(lat), 6)
    return _snap_cached(lon_key, lat_key)


def load_zones(zone_mapping_path):
    if os.path.isabs(zone_mapping_path):
        resolved = zone_mapping_path
    else:
        resolved = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", zone_mapping_path))

    if not os.path.exists(resolved):
        raise FileNotFoundError(
            f"zone mapping not found at '{resolved}'. Run scripts/generate_zone_mapping.py first."
        )

    zones = []
    with open(resolved, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            zones.append(
                {
                    "zone_id": int(row["zone_id"]),
                    "zone_name": row.get("zone_name"),
                    "zone_type": row.get("zone_type"),
                    "lat": float(row["centroid_lat"]),
                    "lon": float(row["centroid_lon"]),
                }
            )

    if not zones:
        raise ValueError(f"zone mapping file '{resolved}' is empty")

    return zones, resolved


def build_spark(args):
    return (
        SparkSession.builder.appName("PortoToCasablancaRemapper")
        .config("spark.hadoop.fs.s3a.endpoint", args.s3_endpoint)
        .config("spark.hadoop.fs.s3a.access.key", args.s3_access_key)
        .config("spark.hadoop.fs.s3a.secret.key", args.s3_secret_key)
        .config("spark.hadoop.fs.s3a.path.style.access", "true")
        .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
        .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false")
        .config(
            "spark.hadoop.fs.s3a.aws.credentials.provider",
            "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider",
        )
        .getOrCreate()
    )


def main():
    args = parse_args()
    global OSRM_BASE_URL
    OSRM_BASE_URL = args.osrm_base_url.rstrip("/")

    spark = build_spark(args)
    spark.sparkContext.setLogLevel("WARN")
    zones, resolved_zone_path = load_zones(args.zone_mapping_path)

    print(f"Using zone mapping from {resolved_zone_path}")

    print(f"Reading dataset from {args.input_path}")
    df = spark.read.option("header", "true").option("inferSchema", "true").csv(args.input_path)

    polyline_schema = ArrayType(ArrayType(DoubleType()))
    casa_lons = [z["lon"] for z in zones]
    casa_lats = [z["lat"] for z in zones]
    casa_lon_min = min(casa_lons)
    casa_lon_max = max(casa_lons)
    casa_lat_min = min(casa_lats) - 0.002
    casa_lat_max = max(casa_lats) + 0.002

    print("Applying Spark-native transformation pipeline...")
    work = (
        df.withColumn("coords", F.from_json(F.col("POLYLINE"), polyline_schema))
        .filter(F.col("coords").isNotNull() & (F.size("coords") > 0))
        .withColumn("pos", F.posexplode(F.col("coords")))
        .withColumn("porto_lon", F.col("col")[0])
        .withColumn("porto_lat", F.col("col")[1])
    )

    porto_lon_clamped = (
        F.when(F.col("porto_lon") < F.lit(PORTO_LON_MIN), F.lit(PORTO_LON_MIN))
        .when(F.col("porto_lon") > F.lit(PORTO_LON_MAX), F.lit(PORTO_LON_MAX))
        .otherwise(F.col("porto_lon"))
    )
    porto_lat_clamped = (
        F.when(F.col("porto_lat") < F.lit(PORTO_LAT_MIN), F.lit(PORTO_LAT_MIN))
        .when(F.col("porto_lat") > F.lit(PORTO_LAT_MAX), F.lit(PORTO_LAT_MAX))
        .otherwise(F.col("porto_lat"))
    )

    work = (
        work.withColumn(
            "casa_lon",
            F.lit(casa_lon_min)
            + ((porto_lon_clamped - F.lit(PORTO_LON_MIN)) / F.lit(PORTO_LON_MAX - PORTO_LON_MIN))
            * F.lit(casa_lon_max - casa_lon_min),
        )
        .withColumn(
            "casa_lat",
            F.lit(casa_lat_min)
            + ((porto_lat_clamped - F.lit(PORTO_LAT_MIN)) / F.lit(PORTO_LAT_MAX - PORTO_LAT_MIN))
            * F.lit(casa_lat_max - casa_lat_min),
        )
    )

    snap_schema = StructType(
        [
            StructField("lon", DoubleType(), False),
            StructField("lat", DoubleType(), False),
        ]
    )

    snap_udf = F.udf(lambda lon, lat: snap_to_road(lon, lat), snap_schema)

    work = (
        work.withColumn("snapped", snap_udf(F.col("casa_lon"), F.col("casa_lat")))
        .withColumn("casa_lon", F.col("snapped.lon"))
        .withColumn("casa_lat", F.col("snapped.lat"))
        .drop("snapped")
    )

    remapped = (
        work.groupBy("TRIP_ID")
        .agg(
            F.collect_list(F.struct(F.col("pos"), F.col("casa_lon"), F.col("casa_lat"))).alias(
                "points_struct"
            )
        )
        .withColumn(
            "points_sorted",
            F.expr("transform(array_sort(points_struct), x -> array(x.casa_lon, x.casa_lat))"),
        )
        .withColumn("POLYLINE", F.to_json(F.col("points_sorted")))
        .withColumn("start_lon", F.expr("points_sorted[0][0]"))
        .withColumn("start_lat", F.expr("points_sorted[0][1]"))
    )

    zone_candidates = F.array(
        *[
            F.struct(
                (
                    F.pow(F.col("start_lat") - F.lit(z["lat"]), F.lit(2.0))
                    + F.pow(F.col("start_lon") - F.lit(z["lon"]), F.lit(2.0))
                ).alias("dist"),
                F.lit(z["zone_id"]).alias("zone_id"),
            )
            for z in zones
        ]
    )

    remapped = remapped.withColumn(
        "CASA_ORIGIN_ZONE",
        F.element_at(F.array_sort(zone_candidates), 1).getField("zone_id"),
    )

    zone_meta = spark.createDataFrame(
        [(z["zone_id"], z["zone_name"], z["zone_type"]) for z in zones],
        ["zone_id", "zone_name", "zone_type"],
    )

    remapped = (
        remapped.join(zone_meta, remapped.CASA_ORIGIN_ZONE == zone_meta.zone_id, "left")
        .drop("zone_id")
        .withColumnRenamed("zone_name", "CASA_ORIGIN_ZONE_NAME")
        .withColumnRenamed("zone_type", "CASA_ORIGIN_ZONE_TYPE")
    )

    base_cols = [c for c in df.columns if c not in {"POLYLINE"}]
    df_out = (
        df.select(*base_cols)
        .join(
            remapped.select(
                "TRIP_ID",
                "POLYLINE",
                "CASA_ORIGIN_ZONE",
                "CASA_ORIGIN_ZONE_NAME",
                "CASA_ORIGIN_ZONE_TYPE",
            ),
            on="TRIP_ID",
            how="inner",
        )
    )

    print(f"Writing remapped data to {args.output_path}")
    df_out.write.mode("overwrite").option("compression", "snappy").parquet(args.output_path)

    print("Done - Issue 4 remapping completed.")
    spark.stop()


if __name__ == "__main__":
    main()
